### PR TITLE
Feature/issue#26 optimize seo

### LINKED ISSUE #36: Workaround for Retina Screens
## Problem
This issue will follow the related issue with the rive-js package (linked below). The current workaround is to make the canvas twice as large as it needs to be and then scale it down so that it looks great on retina screens (this make no difference on non-retina screens, as far as I can tell).

## Workaround
https://codepen.io/getflourish/pen/XWNOojM

---
See https://github.com/rive-app/rive-wasm/issues/48

### PR DESCRIPTION
**Pull request by notjustinshaw**

### CODE REVIEW

**Comment by notjustinshaw** [comment]
Screen Shot 2021-03-21 at 4 32 37 PM
We should increase the color contrast here between the button background color and the white text (make background color darker probably)

**Comment by notjustinshaw** [comment]
Screen Shot 2021-03-21 at 4 38 21 PM
Much better.

**Comment by notjustinshaw** [comment]
Screen Shot 2021-03-21 at 5 02 33 PM
Almost there...

**Comment by notjustinshaw** [comment]
Screen Shot 2021-03-21 at 7 33 41 PM
Nice.

**Review by sorenrood — APPROVED** [review]
**LGTM**
penguin_dance

**Pull request merged**
