### PR TITLE
Add Google Analytics

### LINKED ISSUE #21: Add Google Analytics
Let's add a Google Analytics tag to the website so we can gaguge traffic before it starts picking up.

### PR DESCRIPTION
**Pull request by notjustinshaw**
Adding Google Analytics to the website. (see #21)

### CODE REVIEW

**Comment by notjustinshaw** [comment]
I sent you an email with a link to the analytics portal: https://analytics.google.com/analytics/web/

**Comment by notjustinshaw** [comment]
Merge when ready 👍🏻

**Comment by sorenrood** [comment]
@justinalexandershaw will do 👍🏻

**Review by sorenrood — APPROVED** [review]
**LGTM**
penguin_dance

**Pull request merged**
